name: 'CATS Restore DB From Snapshot'
description: 'Restore DB from latest Restic Snapshot'
inputs:
  aws-access-key-id:
    description: 'Supply AWS Access Key ID'
    required: true
  aws-secret-access-key:
    description: 'Supply AWS Secret Access Key'
    required: true
  db-host:
    description: 'Supply database host'
    required: true
  db-database:
    description: 'Supply database name'
    required: true
  db-username:
    description: 'Supply database username'
    required: true
  db-password:
    description: 'Supply database password'
    required: true
  restic-filename:
    description: 'Filename for restic snapshot'
    required: false
    default: 'indevets-core-partial.sql.gz'
  restic-repository:
    description: 'Supply Restic Repository config'
    required: true
  restic-password:
    description: 'Supply Restic Password config'
    required: true
  ssh-key-encoded:
    description: 'Supply Base64 encoded SSH Key for DB server'
    required: true
  ssh-username:
    description: 'Supply SSH Username for DB server'
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Restic
      uses: AnimMouse/setup-restic@v1

    - name: Update action_path
      run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash

    - run: restore.sh
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
        DB_DATABASE: ${{ inputs.db-database }}
        DB_HOST: ${{ inputs.db-host }}
        PGPASSWORD: ${{ inputs.db-password }}
        DB_USERNAME: ${{ inputs.db-username }}
        RESTIC_FILENAME: ${{ inputs.restic-filename }}
        RESTIC_PASSWORD: ${{ inputs.restic-password }}
        RESTIC_REPOSITORY: ${{ inputs.restic-repository }}
        SSH_KEY_ENCODED: ${{ inputs.ssh-key-encoded }}
        SSH_USERNAME: ${{ inputs.ssh-username }}
    
    - uses: mxschmitt/action-tmate@v3
      if: failure()
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
        DB_DATABASE: ${{ inputs.db-database }}
        DB_HOST: ${{ inputs.db-host }}
        PGPASSWORD: ${{ inputs.db-password }}
        DB_USERNAME: ${{ inputs.db-username }}
        RESTIC_FILENAME: ${{ inputs.restic-filename }}
        RESTIC_PASSWORD: ${{ inputs.restic-password }}
        RESTIC_REPOSITORY: ${{ inputs.restic-repository }}
        SSH_KEY_ENCODED: ${{ inputs.ssh-key-encoded }}
        SSH_USERNAME: ${{ inputs.ssh-username }}

      
