name: 'K8s: Deploy k8s-manifests'
description: 'Deploy k8s manifests to cluster via GH action'
inputs:
  restic-password:
    description: 'Supply restic password'
    required: true
    
   # todo: add the other input variables

runs:
  using: "composite"
  steps:
    - name: Setup Restic
      uses: AnimMouse/setup-restic@v1

    - name: Update action_path
      run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash

    # todo: rename bash script to restore.sh
    - run: restore.sh
      env:
        RESTIC_PASSWORD: ${{ inputs.restic-password }}

      shell: bash
