name: 'K8s: Deploy k8s-manifests'
description: 'Deploy k8s manifests to cluster via GH action'
inputs:
  restic-password:
    description: 'Supply restic password'
    required: true
    
   # todo: add the other input variables

runs:
  using: "composite"
  steps:
    - name: Setup Restic
      uses: AnimMouse/setup-restic@v1

    - name: Update action_path
      run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash

    # todo: rename bash script to restore.sh
    - run: restore.sh
      env:
        BRANCH_DEPLOY: ${{ inputs.branch-deploy }}
        BRANCH_RELEASE: ${{ inputs.branch-release }}
        KUBE_CONFIG_BASE64: ${{ inputs.kube-config-base64 }}
        DOCKER_CONFIG_BASE64: ${{ inputs.docker-config-base64 }}
      shell: bash
