apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  labels:
    app: promtail
    chart: promtail-2.2.0
    heritage: Helm
    release: loki
  name: loki-promtail
spec:
  allowPrivilegeEscalation: false
  fsGroup:
    rule: RunAsAny
  hostIPC: false
  hostNetwork: false
  hostPID: false
  privileged: false
  readOnlyRootFilesystem: true
  requiredDropCapabilities:
    - ALL
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
    - secret
    - configMap
    - hostPath
    - projected
    - downwardAPI
    - emptyDir
